### ISSUE TITLE
Unreliable

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/rpc-handler#54] opened 2024-10-10 16:07 UTC
pay.ubq.fi has not been working the last few days. rpc manager is not handling errors

![telegram-cloud-photo-size-1-4918431621091274969-y](https://github.com/user-attachments/assets/39832108-72d3-4d6a-a5cb-a8f720a76850)

![telegram-cloud-photo-size-1-4918431621091274966-y](https://github.com/user-attachments/assets/30ac5cf5-add9-441b-804b-f6b6729fc68b)

![telegram-cloud-photo-size-1-4918431621091274963-y](https://github.com/user-attachments/assets/affc0539-ac54-430c-b8e7-dfd6c5b865ef)

**Comment by rndquu** [comment] 2024-10-22 15:01
[This](https://github.com/ubiquity/pay.ubq.fi/blob/9b88dd6ffe04a13650d51a055441696a13047be9/shared/helpers.ts#L32) line suddenly started throwing `✘ [ERROR] [RPCService] Failed to find fastest RPC TypeError: Reduce of empty array with no initial value`

**Comment by Keyrxng** [comment] 2024-10-23 19:18
> [This](https://github.com/ubiquity/pay.ubq.fi/blob/9b88dd6ffe04a13650d51a055441696a13047be9/shared/helpers.ts#L32) line suddenly started throwing `✘ [ERROR] [RPCService] Failed to find fastest RPC TypeError: Reduce of empty array with no initial value`

where was this @rndquu in production or local testing? 

Local requires you pass in `localhost:8545` in my exp testing in pay.ubq.fi

**Comment by rndquu** [comment] 2024-10-24 07:48
> where was this @rndquu in production or local testing?

Local testing with reloadly production credentials

> Local requires you pass in localhost:8545 in my exp testing in pay.ubq.fi

I don't understand where to pass it and why we should even pass anything for `handler.getFastestRpcProvider()` to work

**Comment by Keyrxng** [comment] 2024-10-24 14:15
![image](https://github.com/user-attachments/assets/79738c7e-a72e-4317-804c-667faf334e4c)

![image](https://github.com/user-attachments/assets/a17e2bd0-212f-4118-a95d-ba02497fc525)


https://github.com/ubiquity/pay.ubq.fi/pull/345/files#diff-f74ca1939008bb970e16b2333f4ce8d95a939ba8a409737479a3e9b19515dffbR10

The PR in pay.ubq.fi is ready for review, contains the change and does not present `undefined` or your error.

**Comment by Keyrxng** [comment] 2024-10-24 14:16
If your testing locally you are likely using networkID `31337` and if that's true then that's your `rpc-handler` response from that network as `31337` is a real network so you must manually add your local anvil instance to runtime rpcs

`rpc-handler` could receive a slight update to address this and we can insert the local anvil urls from here but host and port are customizable so I figured best to enforce the consumer of the pkg injects their own local provider

https://github.com/ubiquity/rpc-handler/blob/04f10b4987edb391aeec8bc36eaf3f13a3dd1020/types/constants.ts#L9-L22 - There is logic (which I just noticed is slightly incorrect) to handle this in the package already, it needs fixed by deleting the entry first and then replacing it with anvil, I'm doing the reverse it seems so the delete call doesn't remove it.

**Comment by Keyrxng** [comment] 2024-10-25 12:36
I'm pretty sure this can be closed as unplanned.

1. `permit-generation` was the cause of the down time due to invalid permits.
2. local testing just needs the user to inject their anvil instance.
3. https://github.com/ubiquity/pay.ubq.fi/pull/345#event-14864453233, https://github.com/ubiquity/pay.ubq.fi/pull/352, have been merged without error and things appear to be working.

**Comment by rndquu** [comment] 2024-10-25 15:45
ok, let's see how it goes

**Closed as not planned by rndquu** 2024-10-25 15:45 UTC
Labels: Priority: 4 (Urgent)
